source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "jekyll", "~> 3.9.0"
gem "github-pages", ">= 206", group: :jekyll_plugins

group :jekyll_plugins do
    gem "jekyll-menus", "~> 0.6.1"
    gem "jekyll-paginate-v2", "~> 1.9", ">= 1.9.4"
    gem "jekyll-paginate", "~> 1.1"
    gem 'jekyll-feed', '>= 0.13.0'
    gem 'jekyll-sitemap'    , '>= 1.4.0'
end
